---
- hosts: debian-dev-servers
  pre_tasks:
    - name: Check if Virtualbox guest-additions are installed.
      command: /sbin/lsmod
      register: lsmod
    - name: Get variable for 'uname -r'
      shell: uname -r
      register: uname_r

  roles:
   - role: debian_vbox_guestadditions
     when: "'vboxguest' not in lsmod.stdout and virtualbox_install_additions|default(False)"

    - role: geerlingguy.git


